### PR TITLE
fix(types): resolve type discrepancies between ESM and CJS TypeScript…

### LINKED ISSUE #6955: Discrepancies between types from index.d.cts and index.d.ts
### Describe the bug

As of v1.10.0, the following discrepancies exist between the types from https://github.com/axios/axios/blob/v1.10.0/index.d.cts (CJS) and https://github.com/axios/axios/blob/v1.10.0/index.d.ts (ESM), making their corresponding types incompatible:

## `AxiosHeaders` class

ESM class `AxiosHeaders` [contains](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L77) a `getSetCookie(): string[];` but is missing from its CJS [counterpart](https://github.com/axios/axios/blob/v1.10.0/index.d.cts#L19-L81).

## `AxiosHeaderMatcher` type

ESM type `AxiosHeaderMatcher` is [defined as](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L12):

```typescript
type AxiosHeaderMatcher =
  | string
  | RegExp
  | ((this: AxiosHeaders, value: string, name: string) => boolean);
```

while its CJS counterpart is [defined as](https://github.com/axios/axios/blob/v1.10.0/index.d.cts#L9):
```typescript
type AxiosHeaderMatcher = (
  this: AxiosHeaders,
  value: string,
  name: string,
  headers: RawAxiosHeaders
) => boolean;
```

## `InternalAxiosRequestConfig` interface

ESM interface `InternalAxiosRequestConfig` is [defined as](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L370-L372)
```typescript
export interface InternalAxiosRequestConfig<D = any> extends AxiosRequestConfig<D> {
  headers: AxiosRequestHeaders;
}
```

while its CJS [counterpart](https://github.com/axios/axios/blob/v1.10.0/index.d.cts#L427-L429) is missing the generic type param for `AxiosRequestConfig`:
```typescript
interface InternalAxiosRequestConfig<D = any> extends AxiosRequestConfig {
  headers: AxiosRequestHeaders;
}
```

## `AxiosError` class
ESM class `AxiosError` [contains](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L422-L429) a static method `from`:
```typescript
static from<T = unknown, D = any>(
  error: Error | unknown,
  code?: string,
  config?: InternalAxiosRequestConfig<D>,
  request?: any,
  response?: AxiosResponse<T, D>,
  customProps?: object,
): AxiosError<T, D>;
```
while its CJS [counterpart](https://github.com/axios/axios/blob/v1.10.0/index.d.cts#L83-L112) has no such method.

## `AxiosStatic` interface
ESM interface `AxiosStatic` [contains](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L549-L568) a `mergeConfig` method:
```typescript
export function mergeConfig<D = any>(config1: AxiosRequestConfig<D>, config2: AxiosRequestConfig<D>): AxiosRequestConfig<D>;

//...

export interface AxiosStatic extends AxiosInstance {
  // ...
  mergeConfig: typeof mergeConfig;
}
```

while its CJS [counterpart](https://github.com/axios/axios/blob/v1.10.0/index.d.cts#L529-L545) does not contain such a method.

### To Reproduce

n/a

### Code snippet

```js

```

### Expected behavior

types should be identical between CJS and ESM

### Axios Version

1.10.0

### Adapter Version

n/a

### Browser

n/a

### Browser Version

n/a

### Node.js Version

n/a

### OS

n/a

### Additional Library Versions

```bash
n/a
```

### Additional context/Screenshots

```bash

```

### PR DESCRIPTION
**Pull request by jrnail23**
Resolves #6955 

Reconciles type discrepancies between index.d.ts and index.d.cts.

### CODE REVIEW

File: index.d.cts [hunk 1]
```diff
@@ -6,7 +6,7 @@ type MethodsHeaders = Partial<{
   [Key in axios.Method as Lowercase<Key>]: AxiosHeaders;
 } & {common: AxiosHeaders}>;
 
-type AxiosHeaderMatcher = (this: AxiosHeaders, value: string, name: string, headers: RawAxiosHeaders) => boolean;
```
Comment (jrnail23) [inline index.d.cts:9]: note the `headers` param is not used by the source code, and not present in the ESM types, so I removed it

File: index.d.cts [hunk 2]
```diff
@@ -6,7 +6,7 @@ type MethodsHeaders = Partial<{
...
+type AxiosHeaderMatcher = string | RegExp | ((this: AxiosHeaders, value: string, name: string) => boolean);
```
Comment (jrnail23) [inline index.d.cts:9]: [ESM](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L12)

File: index.d.cts [hunk 3]
```diff
@@ -77,6 +77,8 @@ declare class AxiosHeaders {
   getAuthorization(matcher?: AxiosHeaderMatcher): axios.AxiosHeaderValue;
   hasAuthorization(matcher?: AxiosHeaderMatcher): boolean;
 
+  getSetCookie(): string[];
```
Comment (jrnail23) [inline index.d.cts:80]: [ESM](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L77)

File: index.d.cts [hunk 4]
```diff
@@ -97,6 +99,14 @@ declare class AxiosError<T = unknown, D = any> extends Error {
...
   toJSON: () => object;
   cause?: Error;
+  static from<T = unknown, D = any>(
+    error: Error | unknown,
+    code?: string,
+    config?: axios.InternalAxiosRequestConfig<D>,
+    request?: any,
+    response?: axios.AxiosResponse<T, D>,
+    customProps?: object,
+): AxiosError<T, D>;
```
Comment (jrnail23) [inline index.d.cts:109]: [ESM](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L422-L429)

File: index.d.cts [hunk 5]
```diff
@@ -424,7 +434,7 @@ declare namespace axios {
   // Alias
   type RawAxiosRequestConfig<D = any> = AxiosRequestConfig<D>;
 
-  interface InternalAxiosRequestConfig<D = any> extends AxiosRequestConfig {
+  interface InternalAxiosRequestConfig<D = any> extends AxiosRequestConfig<D> {
```
Comment (jrnail23) [inline index.d.cts:437]: [ESM](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L370-L372)

File: index.d.cts [hunk 6]
```diff
@@ -542,6 +552,7 @@ declare namespace axios {
     formToJSON(form: GenericFormData|GenericHTMLFormElement): object;
     getAdapter(adapters: AxiosAdapterConfig | AxiosAdapterConfig[] | undefined): AxiosAdapter;
     AxiosHeaders: typeof AxiosHeaders;
+    mergeConfig<D = any>(config1: AxiosRequestConfig<D>, config2: AxiosRequestConfig<D>): AxiosRequestConfig<D>;
```
Comment (jrnail23) [inline index.d.cts:555]: [ESM](https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L549-L568)

File: index.d.cts (hunk 4 above)
Comment (jasonsaayman) [reply index.d.cts:109]: pls swap unknown to any here

**Review by jasonsaayman — DISMISSED** [review]
looks good just the swap mentioned as most people do prefer any

File: index.d.cts (hunk 4 above)
Comment (jrnail23) [reply index.d.cts:109]: @jasonsaayman, that comes directly from the existing corresponding ESM types:
https://github.com/axios/axios/blob/v1.10.0/index.d.ts#L423

If I change that here, it would conflict with the existing types.  You sure you want that?

**Comment by jrnail23** [comment]
> looks good just the swap mentioned as most people do prefer any

@jasonsaayman, please see this comment:
https://github.com/axios/axios/pull/6956#discussion_r2198349369

File: index.d.cts (hunk 4 above)
Comment (jasonsaayman) [reply index.d.cts:109]: oh lol sorry ok cool then its fine, this one must have slipped me in the past

**Review by jasonsaayman — APPROVED** [review]
