### PR TITLE
fix(fetch): enhance fetch API detection;

### LINKED ISSUE #6412: v1.7.0 release bug
### Describe the bug

After upgrade to 1.7.0 from 1.6.8, Getting the following error:

node_modules/remote-content/node_modules/axios/dist/node/axios.cjs:3791
})(new Response));
   ^
TypeError: Response is not a constructor

### To Reproduce

upgrade to axios 1.7.0

### Code snippet

_No response_

### Expected behavior

no error happen

### Axios Version

1.7.0

### Adapter Version

_No response_

### Browser

_No response_

### Browser Version

_No response_

### Node.js Version

v16.20.2 (npm v8.19.4)

### OS

_No response_

### Additional Library Versions

_No response_

### Additional context/Screenshots

downgrading to 1.6.8 resolves the issue

### PR DESCRIPTION
**Pull request by DigitalBrainJS**
Fixes #6412

### CODE REVIEW

File: lib/adapters/fetch.js [hunk 1]
```diff
@@ -17,11 +17,11 @@ const fetchProgressDecorator = (total, fn) => {
   }));
 }
 
-const isFetchSupported = typeof fetch !== 'undefined';
-const isReadableStreamSupported = isFetchSupported && typeof ReadableStream !== 'undefined';
+const isFetchSupported = typeof fetch === 'function' && typeof Request === 'function' && typeof Response === 'function';
+const isReadableStreamSupported = isFetchSupported && typeof ReadableStream === 'function';
```
Comment (zhibirc) [inline lib/adapters/fetch.js:21]: Sorry for my 5 cent, but having `isFunction` utility will be more concise, more readable, and guard against typos (`typeof fetch === 'funct1on'` is just silently `false`), as well as increase evolvability, when additional sub-checks should be implemented.
