### PR TITLE
fix(buildFullPath): handle `allowAbsoluteUrls: false` without `baseURL`

### LINKED ISSUE #6832: `TypeError` when specifying `allowAbsoluteUrls: false` without `baseURL`
### Describe the bug

When specifying both the new `allowAbsoluteUrls: false` option, without specifying a `baseURL`, the caller gets a `TypeError`:
```txt
TypeError: Cannot read properties of undefined (reading 'replace')
  141 |   }
  142 |
> 143 |   const response = await axios.request<T>(config)
      |                                ^
  144 |
  145 |   return response
  146 | }
  at combineURLs (../../../../../../home/runner/.yarn/berry/cache/axios-npm-1.8.3-b472059d00-10c0.zip/node_modules/axios/lib/helpers/combineURLs.js:13:15)
  at buildFullPath (../../../../../../home/runner/.yarn/berry/cache/axios-npm-1.8.3-b472059d00-10c0.zip/node_modules/axios/lib/core/buildFullPath.js:19:12)
```

### To Reproduce

1. Execute the code snippet
2. See `TypeError: Cannot read properties of undefined (reading 'replace')`

### Code snippet

```js
axios.get('https://example.com', { allowAbsoluteUrls: false })
```

### Expected behavior

No error

### Axios Version

1.18.3

### Adapter Version

All

### Browser

All

### Browser Version

All

### Node.js Version

All

### OS

All

### Additional Library Versions

```bash

```

### Additional context/Screenshots

```bash

```

### PR DESCRIPTION
**Pull request by mhassan1**
This PR fixes the logic in `buildFullPath` to properly handle the case where `allowAbsoluteUrls` is `false` and `baseURL` is `undefined`; currently, it throws a `TypeError`.

Resolves https://github.com/axios/axios/issues/6832.

### CODE REVIEW

**Comment by mhassan1** [comment]
@jasonsaayman Please take a look when you get a chance. This bug will inevitably hit people who start opting in to a default `allowAbsoluteUrls: false`.

File: lib/core/buildFullPath.js [hunk 1]
```diff
@@ -15,7 +15,7 @@ import combineURLs from '../helpers/combineURLs.js';
  */
 export default function buildFullPath(baseURL, requestedURL, allowAbsoluteUrls) {
   let isRelativeUrl = !isAbsoluteURL(requestedURL);
-  if (baseURL && isRelativeUrl || allowAbsoluteUrls == false) {
+  if (baseURL && (isRelativeUrl || allowAbsoluteUrls == false)) {
```
Comment (thatguyinabeanie) [inline lib/core/buildFullPath.js:18]: i noticed that the docstring for buildFullPath is missing an entry for the `allowAbsoluteUrls` param on line 13 above. this would be a great opportunity to add this in

**Review by thatguyinabeanie — DISMISSED** [review]
1 smol change

File: lib/core/buildFullPath.js (hunk 1 above)
Comment (mhassan1) [reply lib/core/buildFullPath.js:18]: feel free to do that in another pr
