### PR TITLE
fix(fetch-adapter): set User-Agent header to match http adapter

### LINKED ISSUE #7494: Fetch Adapter: Content length header is missing in POST request
using axios 1.13.6, it seems several headers are not included compared to the default adapter.

the headers below are auto generated when using the default adapter but not in the fetch adapter:

- User-Agent
- Content-Length
- Accept-Encoding
- Host
- Connection

### PR DESCRIPTION
**Pull request by OfekDanny**
## Summary

The fetch adapter does not set a `User-Agent` header, causing requests to appear with Node.js's default `node` user agent instead of `axios/<version>`. The HTTP adapter correctly sets this header.

`Content-Length`, `Accept-Encoding`, `Host`, and `Connection` are intentionally not added — these are forbidden headers managed automatically by the Fetch API (see maintainer feedback on #10633).

Fixes #7494

## Changes

- `lib/adapters/fetch.js`: set `User-Agent: axios/<version>` header, mirroring the HTTP adapter, with a no-override guard for user-supplied values

## Checklist

- [x] Code follows axios style conventions
- [x] Tests added/updated
- [x] Conventional commit message used

---
## Summary by cubic
Sets the fetch adapter’s default `User-Agent` to `axios/<version>` to match the Node HTTP adapter and avoid Node’s default `node` UA. Keeps any user-provided `User-Agent` intact.

## Description
- Summary of changes
  - Set `User-Agent: axios/<version>` in the `fetch` adapter with a no-override guard.
  - Merged latest `v1.x` into the branch; no behavior changes.
- Reasoning
  - Aligns behavior with the HTTP adapter and fixes requests showing Node’s default `node` UA. Fixes #7494.
- Additional context
  - Did not add `Content-Length`, `Accept-Encoding`, `Host`, or `Connection` (managed by Fetch and forbidden to set).

## Docs
- Update `/docs/` to document the fetch adapter’s default `User-Agent`, how to override it, and parity with the HTTP adapter.

## Testing
- Added unit tests:
  - Sets `User-Agent` to `axios/<version>` by default.
  - Does not override a user-provided `User-Agent`.
- No further tests needed.

## Semantic version impact
- Patch: bug fix aligning adapter behavior without breaking the API.

<sup>Written for commit d7e0817a2ce6bc6dfa3401e7386c3d24f9d6dae9. Summary will update on new commits.</sup>

### CODE REVIEW

File: lib/adapters/fetch.js [hunk 1]
```diff
@@ -236,6 +237,9 @@ const factory = (env) => {
         }
       }
 
+      // Set User-Agent header if not already set (fetch defaults to 'node' in Node.js)
+      headers.set('User-Agent', 'axios/' + VERSION, false);
```
Comment (WillianAgostini) [inline lib/adapters/fetch.js]: Nice PR! Just a thought: if we add this to the core dispatchRequest method instead of the individual adapters, we can avoid duplication and make it easier to maintain long-term. Thoughts on moving it there?
