### PR TITLE
Fixing requestHeaders.Authorization

### LINKED ISSUE #3286: RequestHeaders.Authorization parameter concatenation failed
#### Describe the bug
In situations that use Basic auth and do not pass the parameter "password" _**requestHeaders.Authorization**_ is concatenated unduly "**: undefined**".

#### To Reproduce
Any request using **Basic Authentication** without passing the parameter "**password**" as an example below.

```js
var axios = require("axios")
const instance = axios.create();
instance.request({
    method: 'POST',
    baseURL: ".../XPTO",
    auth: { username: "janedoe" }}
    ).then(
        // do something
    );
```

#### Expected behavior
To maintain compatibility with previous versions, the proper behavior would be to test if the parameter "**password**" was passed, otherwise concatenate empty.

#### Environment
 - Axios Version [e.g. 0.20.0]
 - Adapter [e.g. XHR/HTTP]
 - Browser [e.g. Chrome, Safari]
 - Browser Version [e.g. 22]
 - Node.js Version [e.g. 13.0.1]
 - OS: [e.g. iOS 12.1.0, OSX 10.13.4]
 - Additional Library Versions [e.g. React 16.7, React Native 0.58.0]

#### Additional context/Screenshots
A problem arising from the lack of compatibility with previous versions is to force all current projects that do not pass a "password" parameter to have to include this parameter with an empty value.

### PR DESCRIPTION
**Pull request by Allanbcruz**
Correction of the requestHeaders.Authorization parameter concatenation.

Close #3286.

Correction of the compatibility of the requestHeaders.Authorization parameter for situations in which the "password" parameter is not passed.

### CODE REVIEW

**Review by chinesedfan — APPROVED** [review]
Fixes regression introduced by #1492. Thanks.

File: test/specs/__helpers.js [hunk 1]
```diff
@@ -76,6 +76,22 @@ setupBasicAuthTest = function setupBasicAuthTest() {
...
+  it('should accept HTTP Basic auth credentials without the password parameter', function (done) {
+    axios('/foo', {
+      auth: {
+        username: 'Aladdin'
+      }
+    });
+
+    setTimeout(function () {
+      var request = jasmine.Ajax.requests.mostRecent();
+      console.log(request.requestHeaders['Authorization'], '\n\n\n');
```
Comment (chinesedfan) [inline test/specs/__helpers.js:88]: Before merging, would you mind deleting this log? As well as another log statement in the next test case (line 105).

Comment (Allanbcruz) [reply test/specs/__helpers.js:88]: No, this log is completely unnecessary.

**Review by Allanbcruz — COMMENTED** [review]
removing logs
