### PR TITLE
Decorate resolve and reject to clear timeout in all cases

### LINKED ISSUE #1004: Axios waits for timeout (when configured) even if nock throws an error
#### Summary

When using nock and axios on the server side (node environment) to mock requests and responses, I ran into an interesting issue when I have axios configured with a timeout value.

If nock is not configured for a particular request, it throws an error: `Error: Nock: No match for request`.
If axios does NOT have a timeout value set, no thread is left open and hanging and the test suite closes as normal. 
If a timeout value IS set, axios waits the entire duration of the timeout before closing. Whats weird is the promise axios returns is rejected by nock (which is how I found that error above) so I have no idea why axios stays open for the full timeout.

The issue is in test runners (specifically Jest) will remain open until all threads are done. With axios hanging open here, our test times ballooned without any visible reason and it took me several hours to trace it to this change that caused it.

I have a simple workaround, if in the test environment don't set a timeout value (or make sure we nock all requests) but it feels like a bug to me that the axios promise throws but yet it remains running.

#### Context

- axios version: *v0.16.2*
- nock version: *v9.0.13*
- jest version: *v20.0.4*
- Environment: *node v6.10.2*

### PR DESCRIPTION
**Pull request by pbarbiero**
Changing from manually placed calls to clear the timeout timer, to decorating the resolve/reject promise functions instead.

Fixes #1004, #459 
Replaces #487

### CODE REVIEW

File: lib/adapters/http.js [hunk 1]
```diff
@@ -15,10 +15,20 @@ var enhanceError = require('../core/enhanceError');
 
 /*eslint consistent-return:0*/
 module.exports = function httpAdapter(config) {
-  return new Promise(function dispatchHttpRequest(resolve, reject) {
+  return new Promise(function dispatchHttpRequest(resolvePromise, rejectPromise) {
+    var timer;
+    var resolve = function resolve(value) {
+      clearTimeout(timer);
+      timer = null;
```
Comment (rubennorte) [inline lib/adapters/http.js]: I know it was in the original code but you don't need to set `timer = null`.

Comment (rubennorte) [inline lib/adapters/http.js]: I know it isn't necessary but could you also remove the ` && !timer` from the condition below? I think it never applies because the timer is only set inside the `if`.

**Comment by rubennorte** [comment]
Could you also remove the ` && !timer` condition from the `if`? It's only set inside it.

**Comment by pbarbiero** [comment]
@rubennorte waiting on  anything else from me at this point?

**Comment by rubennorte** [comment]
@pbarbiero travis isn't working for this specific PR and I'm not sure why. Once I figure it out I'll merge this, but the code looks good to me.

**Comment by igorsechyn** [comment]
This has been an issue for me as well. In my case, I am using axios to make requests from a cli to an external server. If that server is down, i.e. there is no response but ECONNREFUSED error instead, the cli will not exit until the timeout is expired. Would be awesome, if this could be merged.

**Comment by datfinesoul** [comment]
Any chance this will be released in the near future?  I believe it will fix a few timeout issues I've run into, when the request errors.

**Comment by pbarbiero** [comment]
Politely pinging @nickuraltsev  & @rubennorte for a follow up

**Comment by TinOo512** [comment]
Any news on that? Having the same issue

**Comment by pbarbiero** [comment]
@emilyemorehouse I hate to bother you, but any chance you can get us moving forward on this one?

**Comment by emilyemorehouse** [comment]
@pbarbiero no worries! 

I've got a work deadline tomorrow morning, but I'll make sure it gets merged this week. I'll also get it included in the next release. 👍

**Comment by nickuraltsev** [comment]
@pbarbiero Thank you for the fix!
