### PR TITLE
Return http adapter by default

### LINKED ISSUE #2507: DefaultAdapter returns unknown/undefined by default
**Describe the bug**
The Default Adapter returns with out being set if the if/elseif isn't met. This means an axios call (through AWS Amplify API) in nextJS getInitialProps throws  because "Adapter is not a function"

**To Reproduce**
Make a next js project with amplify and init with api. GraphQL uses axios to make the calls. Tracing the stack shows that the axios defaults module does not set the adapter.

**Expected behavior**
The adapter should be set.

**Environment:**
 - Axios Version 0.19.0
 - OS: MacOs
 - Browser Chrome
 - Additional Library Versions Next 9.1.1

**Additional context/Screenshots**

```js
function getDefaultAdapter() {
  var adapter;
  // Only Node.JS has a process variable that is of [[Class]] process
  if (typeof process !== 'undefined' && Object.prototype.toString.call(process) === '[object process]') {
    // For node use HTTP adapter
    adapter = require('./adapters/http');
  } else if (typeof XMLHttpRequest !== 'undefined') {
    // For browsers use XHR adapter
    adapter = require('./adapters/xhr');
  }
  return adapter;
}
```

This is the method. The "Object.prototype.toString.call(process) === '[object process]'" is false because the process in nextJS is "'[object Object]'"

This isn't just an issue with nextJS. An if/elseif should never, imo, fall-through and return a variable that hasn't been set. Throw from there or set a default in an else block.

### PR DESCRIPTION
**Pull request by Alanscut**
#### Instructions

Fixes #2507.

Change the host environment in which js is run

### CODE REVIEW

File: lib/defaults.js [hunk 1]
```diff
@@ -15,11 +15,11 @@ function setContentTypeIfUnset(headers, value) {
 
 function getDefaultAdapter() {
   var adapter;
-  if (typeof XMLHttpRequest !== 'undefined') {
```
Comment (yasuf) [inline lib/defaults.js]: I'd be wary of global window variables

Comment (Alanscut) [reply lib/defaults.js]: I admit that you are right, because we use the XMLHttpRequest object in axios, so judging whether it exists or not is really the best way to judge the browser environment; 
So I will revert the if condition(`typeof XMLHttpRequest !== 'undefined'`) which judging whether it is browsing environment. if not, then we thought it is the nodejs environment by default.

Comment (yasuf) [reply lib/defaults.js]: also please add tests 🙏

**Comment by yasuf** [comment]
Fix for https://github.com/axios/axios/issues/2507

File: lib/defaults.js (hunk 1 above)
Comment (Alanscut) [reply lib/defaults.js]: It will take me some time to add the tests for this paticular scenario...wait for me :joy:

**Comment by Alanscut** [comment]
hi @yasuf ,please check the testcase. I can't reproduce the case in #2507 in existing test environment. But if you think it is necessary, I can try to configure the environment.

File: test/unit/adapters/defaults.js [hunk 2]
```diff
@@ -0,0 +1,14 @@
+var defaults = require('../../../lib/defaults');
+var assert = require('assert');
+
+
+describe('supports httpAdapter with nodejs', function () {
+
+  it('should be HTTP in node', function (done) {
+    assert.equal(typeof defaults.adapter,'function')
+    assert.equal(defaults.adapter.name,'httpAdapter')
```
Comment (rrao24) [inline test/unit/adapters/defaults.js]: spacing

**Comment by MickL** [comment]
Could you please merge to fix #2507 ?

**Comment by MickL** [comment]
@Alanscut @yasuf I tested the PR. Now `http` is chosen correctly within Node.js. Anyway I get the error: `ReferenceError: XMLHttpRequest is not defined`. I used webpack to bundle.

**Comment by Alanscut** [comment]
@MickL Has your problem been solved? Can you provide an example? thanks.
